# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      FOS\UserBundle\Model\UserInterface: sha512
      AppBundle\Entity\Email:
        id: app.sha512_crypt_encoder
    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      fos_userbundle:
        id: fos_user.user_provider.username
      email_client:
        entity:
          class: AppBundle:Email
          property: username
          # if you're using multiple entity managers
          # manager_name: customer
#        in_memory:
#            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

        email:
          pattern: ^/
          http_basic: ~
          provider: email_client
#          anonymous: ~
#          form_login:
#            login_path: login
#            check_path: login
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

#        main:
#          pattern: ^/
#            form_login:
#              provider: fos_userbundle
#              csrf_token_generator: security.csrf.token_manager
              # if you are using Symfony < 2.8, use the following config instead:
              # csrf_provider: form.csrf_provider
#            logout:       true
#            anonymous:    true

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: ROLE_ADMIN }
          - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }
#          - { path: ^/email/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#          - { path: ^/email/, roles: ROLE_CUSTOMER }

#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
