# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.sha512_crypt_encoder:
          class: AppBundle\Security\Core\Encoder\Sha512CryptEncoder

  app.property_type_extension:
          class: AppBundle\Form\Extension\PropertyTypeExtension
          tags:
              - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#  appbundle.form.type.alias:
#    class: AppBundle\Form\AliasType
#    arguments: ["@doctrine.orm.entity_manager"]
#    tags:
#    - { name: form.type, alias: alias }
