# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.sha512_crypt_encoder:
          class: AppBundle\Security\Core\Encoder\Sha512CryptEncoder
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#  appbundle.form.type.alias:
#    class: AppBundle\Form\AliasType
#    arguments: ["@doctrine.orm.entity_manager"]
#    tags:
#    - { name: form.type, alias: alias }
